version: 2
updates:
  # Python - x402
  - package-ecosystem: "pip"
    directory: "/x402/server/python"
    schedule:
      interval: "weekly"
      day: "thursday"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Node - x402
  - package-ecosystem: "npm"
    directory: "/x402/server/node-typescript"
    schedule:
      interval: "weekly"
      day: "thursday"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Node - mpp
  - package-ecosystem: "npm"
    directory: "/mpp/server/node-typescript"
    schedule:
      interval: "weekly"
      day: "thursday"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
